import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "simplifiedDocument" model, go to https://article-simplifier.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v1",
  storageKey: "vUosULgS7wnI",
  comment:
    "This model represents a simplified version of a document, generated by AI, and is associated with a specific user and original document.",
  fields: {
    originalDocument: {
      type: "belongsTo",
      validations: { required: true },
      parent: { model: "document" },
      storageKey: "rZDoWnfdh4zw",
    },
    simplificationLevel: {
      type: "enum",
      acceptMultipleSelections: false,
      acceptUnlistedOptions: false,
      options: ["basic", "intermediate", "advanced"],
      validations: { required: true },
      storageKey: "HDpxD9GKEUMN",
    },
    simplifiedContent: {
      type: "richText",
      validations: { required: true },
      storageKey: "TchYkz6IPkfh",
    },
    user: {
      type: "belongsTo",
      validations: { required: true },
      parent: { model: "user" },
      storageKey: "VttRWb4Ce7So",
    },
  },
};
